# Main page title
title: "Majo Texture Pack (Minecraft 1.8)"

# Your name
name: "Igor Kowalczyk"

# Name of project
project: "Majo Texture Pack"

# Contact E-Mail (Public!)
email: "xxmajonezxx@gmail.com"

# Description
description: "MAJO Texture pack. For Minecraft 1.8"

# Base url (Not link! Only dir.
baseurl: "/txt"

# Repo from github
repo: "txt"

# Branch (eg. master)
branch: "master"

# Github username (no link) - if you don't have - leave blank
github_username:  "igorkowalczyk"

# First Launch of the site (displays in footer)
first-launch: "2019"

# Timezone
timezone: "Europe/Warsaw"

# Markdown and Default theme
markdown: kramdown
theme: minima

# Exclude files
exclude:
 - Gemfile
 - Gemfile.lock

# Tracking id - if you don't have - leave blank
tracking_id: "UA-153609882-1"

# Verification ID - if you don't have - leave blank
verification: "-wuCsk4qLolXEPSUTGX7YBxywcyNNf5HS2ClzgEWxNY"
